### ISSUE TITLE
Feature Request - Highlights, Cards, Auto Complete, AI Answers 

### ISSUE THREAD

**Issue by fire17** [jgravelle/Groqqle#1]
This looks like a nice project,
Obvious next steps is to show fast info, like asking google the following:
- time in Hawaii 
- weather in < somewhere >
- height of mount everest 
- what is a dog

All of which get a highlighted top card with a straight forward answer.

Next thing is to add Perplexity style llm based answers to questions

Add auto complete 

Add a task-list, that future agentic ai can start a mission 

And improve the styling haha 
Lemme know if your interested in making this into a Mac/PC app 
All the best!

**Comment by jgravelle** [comment]
Great suggestions!

I actually considered a "retro" theme that would have been a throwback to the original G**gle site...
![image](https://github.com/user-attachments/assets/82dbfa95-7116-46ec-8dc3-fe7cb6b4b573)

FWIW, the query "Weather in Sheboygan" returned:
{
  "title": "10-Day Weather Forecast for Sheboygan, WI",
  "url": "https://weather.com/weather/tenday/l/Sheboygan+WI?canonicalCityId=5b5f72b00f4a96cc184f2c7c62805fb8619516eabec8c9b4de22324e5b34a3dc",
  "description": "Partly cloudy with late night showers or thunderstorms. A few storms may be severe. Low 72F. SW winds at less than 5 mph, increasing to 10 to 15 mph. Chance of ..."
}

"height of Mt. Everest" gave me:
{
  "title": "Mount Everest",
  "url": "https://en.wikipedia.org/wiki/Mount_Everest",
  "description": "Its elevation (snow height) of8,848.86 m(29,031 ft 8+1⁄2 in) was most recently established in 2020 by the Chinese and Nepali authorities. Mount Everest."
}

... and "What is a dog?" resulted in:
{
  "title": "Dog",
  "url": "https://en.wikipedia.org/wiki/Dog",
  "description": "The dog (Canis familiaris or Canis lupus familiaris) isa domesticated descendant of the wolf. Also called the domestic dog, it was domesticated from an ..."
}

Auto-complete is totally doable but would eat tokens like I eat popcorn.

And if you want to fork this to the Mac, have at ye!  You have my blessing...
