### ISSUE TITLE
Add Exa Search (which is a semantic search engine) for advanced web search

### ISSUE THREAD

**Issue by jbdatascience** [jgravelle/Groqqle#3]
I think it would be a very good idea to add Exa Search (which is a semantic search engine, and in that sense an advanced web search tool, having an API !) to the web search tools in this Groqqle application !

Here are some links to Exa:
https://exa.ai/
The search engine for AI
The Exa API finds the best content on the web using embeddings

https://dashboard.exa.ai/playground

DOCS:
https://docs.exa.ai/reference/getting-started

**Comment by jgravelle** [comment]
Exa is pay-as-you-go.  Groqqle's free.  Find me a free exa API and I'll play with it...
-jjg
