### ISSUE TITLE
What are the rate limits on the search tool used?

### ISSUE THREAD

**Issue by jbdatascience** [jgravelle/Groqqle#8]
I find Groqqle a fantastic tool!
I am experimenting with it and am planning to use it in applications I am will develop.

I am wondering: What are the rate limits on the search tool used? As far as I can see it all depends on Google search. So I think rate limits / requests per day will probably apply. 

Can you shed any light on this?

PS: I love your humor in your video’s!

**Comment by jgravelle** [comment]
You think correctly!  No limit.

My videos love you, too.  But they just want to be friends...


-jjg

**Comment by jbdatascience** [comment]
> You think correctly! No limit.
> 
> My videos love you, too. But they just want to be friends...
> 
> -jjg

Then I must keep "searching". Give me a searchtool for that :-)  ....
